CREATE TABLE SECURITY_USERS
(
    ID       VARCHAR(32) NOT NULL UNIQUE,
    PROVIDER VARCHAR(32),
    EMAIL    VARCHAR(64) UNIQUE,
    LOGIN    VARCHAR(64),
    USERNAME VARCHAR(64),
    PASSWORD VARCHAR(128),
    ENABLED  BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO SECURITY_USERS (`ID`, LOGIN, EMAIL, PASSWORD, ENABLED)
VALUES ('ADMIN-1', 'ADMIN', 'admin@localhost', '$2a$10$eF9BK9TajRVWGFRxa9y2HuX46Sq8ZchiL0Vts408ing2UVc6rtCtm', 1);