CREATE TABLE SECURITY_ROLES
(
    ID   VARCHAR(32) NOT NULL UNIQUE,
    ROLE VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO SECURITY_ROLES (ID, ROLE)
VALUES('ROLE-1', 'ROLE_ADMIN');
INSERT INTO SECURITY_ROLES (ID, ROLE)
VALUES('ROLE-2', 'ROLE_USER');
