CREATE TABLE SECURITY_ROLES_PRIVILEGES
(
    ROLE VARCHAR(250) NOT NULL,
    PRIVILEGE VARCHAR(32) NOT NULL,
    FOREIGN KEY (ROLE) REFERENCES SECURITY_ROLES(ROLE),
    FOREIGN KEY (PRIVILEGE) REFERENCES SECURITY_PRIVILEGES(PRIVILEGE)
);

INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE, PRIVILEGE)
VALUES ('ADMIN', 'READ');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE, PRIVILEGE)
VALUES ('ADMIN', 'CREATE');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE, PRIVILEGE)
VALUES ('ADMIN', 'UPDATE');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE, PRIVILEGE)
VALUES ('ADMIN', 'DELETE');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE, PRIVILEGE)
VALUES ('ADMIN', 'SYSTEM');

INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE, PRIVILEGE)
VALUES ('MANAGER', 'READ');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE, PRIVILEGE)
VALUES ('MANAGER', 'CREATE');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE, PRIVILEGE)
VALUES ('MANAGER', 'UPDATE');

INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE, PRIVILEGE)
VALUES ('USER', 'READ');