CREATE TABLE SECURITY_ROLES
(
    ROLE VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO SECURITY_ROLES (ROLE)
VALUES('ADMIN');
INSERT INTO SECURITY_ROLES (ROLE)
VALUES('MANAGER');
INSERT INTO SECURITY_ROLES (ROLE)
VALUES('USER');
