CREATE TABLE SECURITY_PRIVILEGES
(
    PRIVILEGE VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO SECURITY_PRIVILEGES (PRIVILEGE)
VALUES('READ');
INSERT INTO SECURITY_PRIVILEGES (PRIVILEGE)
VALUES('CREATE');
INSERT INTO SECURITY_PRIVILEGES (PRIVILEGE)
VALUES('UPDATE');
INSERT INTO SECURITY_PRIVILEGES (PRIVILEGE)
VALUES('DELETE');
INSERT INTO SECURITY_PRIVILEGES (PRIVILEGE)
VALUES('SYSTEM');
