CREATE TABLE SECURITY_ROLES_PRIVILEGES
(
    ROLE_ID VARCHAR(32) NOT NULL,
    PRIVILEGE_ID VARCHAR(32) NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES SECURITY_ROLES(ID),
    FOREIGN KEY (PRIVILEGE_ID) REFERENCES SECURITY_PRIVILEGES(ID)
);

INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID)
VALUES ('ROLE-1', 'PRIVILEGE-1');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID)
VALUES ('ROLE-1', 'PRIVILEGE-2');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID)
VALUES ('ROLE-1', 'PRIVILEGE-3');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID)
VALUES ('ROLE-1', 'PRIVILEGE-4');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID)
VALUES ('ROLE-1', 'PRIVILEGE-5');

INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID)
VALUES ('ROLE-2', 'PRIVILEGE-1');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID)
VALUES ('ROLE-2', 'PRIVILEGE-2');
INSERT INTO SECURITY_ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID)
VALUES ('ROLE-2', 'PRIVILEGE-3');