CREATE TABLE SECURITY_ROLES
(
    ID   VARCHAR(32) NOT NULL UNIQUE,
    ROLE VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO SECURITY_ROLES (ID, ROLE)
VALUES('ROLE-ADMIN', 'ROLE_ADMIN');
INSERT INTO SECURITY_ROLES (ID, ROLE)
VALUES('ROLE-USER', 'ROLE_USER');
INSERT INTO SECURITY_ROLES (ID, ROLE)
VALUES('ROLE-OAUTH2-USER', 'ROLE_OAUTH2_USER');
