CREATE TABLE SECURITY_PRIVILEGES
(
    ID          VARCHAR(32) NOT NULL UNIQUE,
    PRIVILEGE   VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO SECURITY_PRIVILEGES (ID, PRIVILEGE)
VALUES('PRIVILEGE-1', 'READ');
INSERT INTO SECURITY_PRIVILEGES (ID, PRIVILEGE)
VALUES('PRIVILEGE-2', 'CREATE');
INSERT INTO SECURITY_PRIVILEGES (ID, PRIVILEGE)
VALUES('PRIVILEGE-3', 'UPDATE');
INSERT INTO SECURITY_PRIVILEGES (ID, PRIVILEGE)
VALUES('PRIVILEGE-4', 'DELETE');
INSERT INTO SECURITY_PRIVILEGES (ID, PRIVILEGE)
VALUES('PRIVILEGE-5', 'SYSTEM');
