CREATE TABLE SECURITY_USERS_ROLES
(
    LOGIN VARCHAR(250) NOT NULL,
    ROLE VARCHAR(32) NOT NULL,
    FOREIGN KEY (LOGIN) REFERENCES SECURITY_USERS(LOGIN),
    FOREIGN KEY (ROLE) REFERENCES SECURITY_ROLES(ROLE)
);

INSERT INTO SECURITY_USERS_ROLES (LOGIN, ROLE)
VALUES ('ADMIN', 'USER');
INSERT INTO SECURITY_USERS_ROLES (LOGIN, ROLE)
VALUES ('ADMIN', 'ADMIN');
INSERT INTO SECURITY_USERS_ROLES (LOGIN, ROLE)
VALUES ('MANAGER', 'MANAGER');
INSERT INTO SECURITY_USERS_ROLES (LOGIN, ROLE)
VALUES ('MANAGER', 'USER');
