CREATE TABLE DF_USERS_REF (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    EXTERNAL_USER_ID VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE DF_FORMS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    STATUS ENUM('ACTIVE', 'INACTIVE', 'DELETED') NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES DF_USERS_REF(USER_ID)
);

CREATE TABLE DF_FORM_FIELDS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID INT NOT NULL,
    FIELD_TYPE_ID INT NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    STATUS ENUM('ACTIVE', 'INACTIVE', 'DELETED') NOT NULL,
    FOREIGN KEY (FORM_ID) REFERENCES DF_FORMS(ID),
    FOREIGN KEY (FIELD_TYPE_ID) REFERENCES DF_FORM_FIELD_TYPES(ID)
);

CREATE TABLE DF_FORM_FIELD_TYPES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ELEMENT_TYPE ENUM('TEXT', 'NUMBER', 'SELECT', 'RADIO', 'CHECKBOX', 'TEXTAREA', 'DATE', 'EMAIL', 'URL') NOT NULL
);

CREATE TABLE DF_FORM_FIELD_PARAMETERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_FIELD_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VALUE TEXT NOT NULL,
    FOREIGN KEY (FORM_FIELD_ID) REFERENCES DF_FORM_FIELDS(ID)
);

CREATE TABLE DF_FORM_FIELD_OPTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIELD_ID INT NOT NULL,
    OPTION_VALUE VARCHAR(255) NOT NULL,
    OPTION_LABEL VARCHAR(255) NOT NULL,
    FOREIGN KEY (FIELD_ID) REFERENCES DF_FORM_FIELDS(ID)
);

CREATE TABLE DF_FORM_RESPONSES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FORM_ID) REFERENCES DF_FORMS(ID)
);

CREATE TABLE DF_FORM_FIELD_RESPONSES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_RESPONSE_ID INT NOT NULL,
    FORM_FIELD_ID INT NOT NULL,
    VALUE TEXT NOT NULL,
    FOREIGN KEY (FORM_RESPONSE_ID) REFERENCES DF_FORM_RESPONSES(ID),
    FOREIGN KEY (FORM_FIELD_ID) REFERENCES DF_FORM_FIELDS(ID)
);

CREATE TABLE DF_FORM_CONFIG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID INT NOT NULL,
    CONFIG_NAME VARCHAR(255) NOT NULL,
    CONFIG_VALUE TEXT NOT NULL,
    FOREIGN KEY (FORM_ID) REFERENCES DF_FORMS(ID)
);

CREATE TABLE DF_FORM_FIELD_CONFIG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_FIELD_ID INT NOT NULL,
    CONFIG_NAME VARCHAR(255) NOT NULL,
    CONFIG_VALUE TEXT NOT NULL,
    FOREIGN KEY (FORM_FIELD_ID) REFERENCES DF_FORM_FIELDS(ID)
);

CREATE TABLE DF_FORM_DEFAULT_VALUES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID INT NOT NULL,
    FIELD_ID INT NOT NULL,
    DEFAULT_VALUE TEXT NOT NULL,
    FOREIGN KEY (FORM_ID) REFERENCES DF_FORMS(ID),
    FOREIGN KEY (FIELD_ID) REFERENCES DF_FORM_FIELDS(ID)
);