# Server
server.port: 8077
server.servlet.context-path: /
server.error.whitelabel.enabled: false
# Management
management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway
# Endpoints
endpoints:
  shutdown:
    enabled: true
    sensitive: false
# Spring

spring:
  h2:
    console:
      enabled: false
  application:
    admin:
      enabled: false
      jmx-name: org.springframework.boot:type=API,name=APIApplication
  banner:
    location: classpath:banner.txt
  config:
    import:
      - classpath:db/data-source-h2.properties
      - classpath:db/spring-jpa-hibernate.properties
      - classpath:db/flyway.properties
      - classpath:db/h2.properties
  flyway:
    enabled: true
# Application
application:
  title: StartForm-API
  version: 1.0-beta

# Http Security
http-security:
  h2-console: /console/**
  security-path: /security
  permit-all:
    - ${http-security.security-path}/oauth/**
    - ${http-security.h2-console}