# Server
server.port: 8099
server.servlet.context-path: /
server.error.whitelabel.enabled: false
server:
  servlet:
    session:
      cookie.name: J_DF_SESSION_ID
# Management
management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway
# Endpoints
endpoints:
  shutdown:
    enabled: true
    sensitive: false
# Spring
spring:
  application:
    admin:
      enabled: false
      jmx-name: org.springframework.boot:type=Web,name=WebApplication
  banner:
    location: classpath:banner.txt
  config:
    import:
      - classpath:application-sensitive.yml
      - classpath:db/data-source.properties
      - classpath:db/spring-jpa-hibernate.properties
      - classpath:db/flyway.properties
      - classpath:db/h2.properties
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            redirectUri: '{baseUrl}/secure/oauth2/callback/{registrationId}'
          google:
            redirectUri: '{baseUrl}/secure/oauth2/callback/{registrationId}'
# Application
application:
  version: 1.0-beta
  name: Dynamic Forms
  locale:
    cookie-name: J_DF_LOCALE
    cookie-max-age: 2592000

# Pebble
pebble:
  suffix: .html
  cache: false
  exposeRequestAttributes: true

# Http Security
http-security:
  h2-console: /console
  security-path: /secure
  oauth2-path: /oauth2
  login-page: ${http-security.security-path}/oauth2
  success-redirect: ${http-security.security-path}/check
  permit-all:
    - ${http-security.security-path}/**
    - ${http-security.h2-console}/**
    - ${http-security.oauth2-path}/**
    - "/js/**"
    - "/css/**"
    - "/images/**"

  form-login:
    processing-url: ${http-security.security-path}/processing
    login: ${http-security.security-path}/login
    loginSuccess: ${http-security.login-page}?actionStatus=login-success
    loginFailure: ${http-security.login-page}?actionStatus=login-failed
    logout: ${http-security.security-path}/logout
    logoutSuccess: ${http-security.login-page}?actionStatus=logout-success
    username: username
    password: password
  remember-me:
    cookie-name: J_DF_WEB_SECURITY
    parameter-name: remember-me
    secret-key: ${ENV_REMEMBER_ME_SECRET_KEY:A69Spring!}
    validity-seconds: 86400
  session-cookie: ${server.servlet.session.cookie.name}
  oauth2-security:
    redirect-endpoint: ${http-security.security-path}/oauth2/callback/*
    authorization-endpoint: ${http-security.security-path}/oauth2/authorize