# Server
server.port: 8099
server.servlet.context-path: /
server.error.whitelabel.enabled: false
server:
  servlet:
    session:
      cookie.name: J_DF_SESSION_ID
# Management
management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway
# Logging
logging:
  level:
    org.springframework.security: DEBUG
# Endpoints
endpoints:
  shutdown:
    enabled: true
    sensitive: false
# Spring
spring:
  application:
    admin:
      enabled: false
      jmx-name: org.springframework.boot:type=Web,name=WebApplication
  banner:
    location: classpath:banner.txt
  config:
    import:
      - classpath:application-sensitive.yml
      - classpath:db/data-source.properties
      - classpath:db/spring-jpa-hibernate.properties
      - classpath:db/flyway.properties
      - classpath:db/h2.properties
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            redirectUri: '{baseUrl}/secure/oauth2/callback/{registrationId}'
            scope:
              - read:user
              - user:email
          google:
            redirectUri: '{baseUrl}/secure/oauth2/callback/{registrationId}'
# Application
application:
  version: 1.0-beta
  name: Dynamic Forms
  homeUrl: /index/home
  theme:
    cookieName: J_DF_THEME
    defaultTheme: lumen
    cookiePath: /
    cookieMaxAge: 604800
  locale:
    cookie-name: J_DF_LOCALE
    cookie-max-age: 2592000

# Pebble
pebble:
  suffix: .html
  cache: false
  exposeRequestAttributes: true

# Http Security
http-security:
  h2Console: /console
  securityPath: /secure
  permit-all:
    - ${http-security.security-path}/login
    - ${http-security.security-path}/perform
    - ${http-security.security-path}/oauth2
    - ${http-security.h2-console}/**
    - "/js/**"
    - "/css/**"
    - "/images/**"

  formLogin:
    processingUrl: ${http-security.securityPath}/perform
    baseUrl: ${http-security.securityPath}/login
    successUrl: /index/home?authorizationStatus=formLogin
    failureUrl: ${http-security.formLogin.baseUrl}?authorizationStatus=failed
    logoutUrl: ${http-security.securityPath}/logout
    logoutSuccessUrl: ${http-security.formLogin.baseUrl}?authorizationStatus=logoutSuccess
    username: username
    password: password

  oauth2:
    baseUrl: ${http-security.security-path}/oauth2
    successUrl: /index/home?authorizationStatus=oauth2
    failureUrl: ${http-security.oauth2.baseUrl}?authorizationStatus=failed
    redirectEndpoint: ${http-security.oauth2.baseUrl}/callback/*
    authorizationEndpoint: ${http-security.oauth2.baseUrl}/authorize

  remember-me:
    cookieName: J_DF_WEB_SECURITY
    parameterName: remember-me
    secretKey: ${ENV_REMEMBER_ME_SECRET_KEY:A69Spring!}
    validitySeconds: 86400

  session-cookie: ${server.servlet.session.cookie.name}