CREATE TABLE SECURITY_PRIVILEGES
(
    ID          VARCHAR(32) NOT NULL UNIQUE,
    PRIVILEGE   VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO SECURITY_PRIVILEGES (ID, PRIVILEGE)
VALUES('PVL-READ', 'READ');
INSERT INTO SECURITY_PRIVILEGES (ID, PRIVILEGE)
VALUES('PVL-CREATE', 'CREATE');
INSERT INTO SECURITY_PRIVILEGES (ID, PRIVILEGE)
VALUES('PVL-UPDATE', 'UPDATE');
INSERT INTO SECURITY_PRIVILEGES (ID, PRIVILEGE)
VALUES('PVL-DELETE', 'DELETE');
INSERT INTO SECURITY_PRIVILEGES (ID, PRIVILEGE)
VALUES('PVL-SYS', 'SYSTEM');
